version: '2'

services:
   nginx:
      build:
         context: ./
         dockerfile: Dockerfile.nginx
      env_file:
        - ./env.local
      ports:
         - "8080:8080"

   webapp:
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - "9090:9090"
      env_file:
         - ./env.local
      volumes:
         - $HOME/botanist/repos:/botanist/repos
