all: nginx botanist

nginx:
	docker build -f Dockerfile.nginx -t sproutsocial/botanist-nginx .

botanist:
	docker build -f Dockerfile -t sproutsocial/botanist .

push-all: push-botanist push-nginx

push-nginx:
	docker push sproutsocial/botanist-nginx:latest

push-botanist:
	docker push sproutsocial/botanist:latest
